# This crate should NOT be upstreamed to crates.io; it is only intended for 
# PARSEC testing purposes (both locally and on CI)
[package]
name = "e2e_tests"
version = "0.1.0"
authors = ["Anton Antonov <anton.antonov@arm.com>",
           "Paul Howard <paul.howard@arm.com>",
           "Ionut Mihalcea <ionut.mihalcea@arm.com>",
           "Hugues de Valon <hugues.devalon@arm.com>"]
description = "End to end testing framework for PARSEC"
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
serde = { version = "1.0.115", features = ["derive"] }
#parsec-client = { git = "https://github.com/parallaxsecond/parsec-client-rust", rev = "3f7dfc7bd06bea7cb3aa38cdcb270af7b8899f89", features = ["testing"] }
parsec-client = { git = "ssh://git@portal-ua.globallogic.com/arm-pelion-egde/parsec-rust-client.git", branch = "calib-integration", features = ["testing"] }
log = "0.4.11"
rand = "0.7.3"

[patch.crates-io]
psa-crypto = { git = "https://github.com/parallaxsecond/rust-psa-crypto", rev = "22a505bedce1c21246ce5c3cf41ea97b0b781830" }

[dev-dependencies]
ring = "0.16.15"
env_logger = "0.7.1"
rsa = "0.3.0"
picky-asn1-x509 = "0.3.2"
base64 = "0.12.3"
num_cpus = "1.13.0"
picky-asn1-der = "0.2.4"
picky-asn1 = "0.3.0"
sha2 = "0.9.1"

[features]
mbed-crypto-provider = []
tpm-provider = []
pkcs11-provider = []
cryptoauthlib-provider = []
all-providers = ["pkcs11-provider","tpm-provider","mbed-crypto-provider","cryptoauthlib-provider"]
